kind: Service
apiVersion: v1
metadata:
  name: frontend-demo-service
  namespace: default
spec:
  selector:
    app: frontend-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    strategy.spinnaker.io/use-source-capacity: 'true'
  name: frontend-demo
  namespace: default
  labels:
    app: frontend-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      applicationName: frontend-demo
  template:
    metadata:
      labels:
        applicationName: frontend-demo
    spec:
      containers:
        - name: demo-frontend
          image: 134925024091.dkr.ecr.eu-west-2.amazonaws.com/demo-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80