kind: Service
apiVersion: v1
metadata:
  name: frontend-demo-service
  namespace: default
spec:
  selector:
    frontedBy: frontend-demo-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service frontend-demo-service"]'
  name: frontend-demo
  namespace: default
  labels:
    app: frontend-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-demo
  template:
    metadata:
      labels:
        app: frontend-demo
    spec:
      containers:
        - name: demo-frontend
          image: 134925024091.dkr.ecr.eu-west-2.amazonaws.com/demo-frontend
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-frontend-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend-demo
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50